name = "GniJulia"
uuid = "793bd386-0bf3-4700-825e-04ccf9225211"
authors = ["Junpeng Gao"]
version = "0.1.0"

[compat]
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
